[package]
name = "sp1-tee-private-server"
version.workspace = true
edition.workspace = true


[dependencies]
anyhow.workspace = true
bincode.workspace = true
alloy-primitives.workspace = true
clap.workspace = true
dotenv.workspace = true
futures.workspace = true
lru.workspace = true
tokio.workspace = true
tracing.workspace = true

sp1-sdk.workspace = true
sp1-prover.workspace = true

sp1-tee-private-types.workspace = true

tonic.workspace = true

async-stream = "0.3.6"
dstack-sdk = { git = "https://github.com/Dstack-TEE/dstack.git" }
