[package]
name = "sp1-tee-private-types"
version.workspace = true
edition.workspace = true

[dependencies]
sp1-sdk.workspace = true

serde.workspace = true
tonic.workspace = true

[build-dependencies]
prost-build.workspace = true
tonic-build.workspace = true